/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Connect.connect;
import dao.HoaDonDao;
import entity.HoaDonBanHang;
import java.awt.List;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GMT
 */
public class FrmHoaDon extends javax.swing.JPanel {
    ArrayList<HoaDonBanHang> listHoaDon = new ArrayList<HoaDonBanHang>();
       private javax.swing.table.DefaultTableModel modelTBHoaDon;
    /**
     * Creates new form FrmHoaDon
     */
    public FrmHoaDon() throws SQLException {
        initComponents();
        try {
             connect.getInstance().connect();
        
            renderListHoaDon();
        } catch (Exception e) {
        }
    }
/*
        Hoa Don
    */
    //dua du lieu HoaDon len Table
	private void renderListHoaDon() {
		 HoaDonDao hoaDonDao = new HoaDonDao();
                 String[] title = { "MaHD", "Ngày Tạo", "Khách Hàng", "Số lượng", "Tổng Tiền", "Tiền Khách Đưa", "Nhân Viên", "Ghi Chú"};
		 listHoaDon  = hoaDonDao.getDsHoaDon();
                modelTBHoaDon = new DefaultTableModel(title,0);
		for(HoaDonBanHang s : listHoaDon) {
			String[] rowData = {
				s.getMaHD(),changeDateToString(s.getNgayLapHD()),s.getMaKH(),String.valueOf(s.getSoLuong()),String.valueOf(s.getTongTien()),
                            String.valueOf(s.getTienKhachDua()),s.getMaNV(),s.getGhiChu()
			};
                       
			modelTBHoaDon.addRow(rowData);
		}
               
		tbHoaDon.setModel(modelTBHoaDon);
	}
         /*
            Chuyen tu date sang String
            @param date Date
            return String
        */
         public String changeDateToString(Date date){
            
                DateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");

                String dateString  = df.format(date);
                return dateString;
          }
         
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtSearchHD = new javax.swing.JTextField();
        btnShowHD = new javax.swing.JButton();
        btnSearchHD = new javax.swing.JButton();
        jDateChoiseHD = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDon = new javax.swing.JTable();

        jPanel1.setBackground(java.awt.Color.white);

        txtSearchHD.setBackground(java.awt.Color.white);
        txtSearchHD.setText("Nhập mã hóa đơn...");
        txtSearchHD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchHDFocusGained(evt);
            }
        });

        btnShowHD.setBackground(new java.awt.Color(21, 151, 229));
        btnShowHD.setForeground(java.awt.Color.white);
        btnShowHD.setText("Hiển thị Hóa Đơn");
        btnShowHD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowHD.setEnabled(false);
        btnShowHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowHDMouseClicked(evt);
            }
        });

        btnSearchHD.setBackground(new java.awt.Color(21, 151, 229));
        btnSearchHD.setForeground(java.awt.Color.white);
        btnSearchHD.setText("Tìm Kiếm");
        btnSearchHD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchHDMouseClicked(evt);
            }
        });
        btnSearchHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHDActionPerformed(evt);
            }
        });

        jDateChoiseHD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateChoiseHDFocusLost(evt);
            }
        });
        jDateChoiseHD.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jDateChoiseHDCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jDateChoiseHDInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearchHD, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchHD, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnShowHD, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jDateChoiseHD, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnShowHD, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChoiseHD, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(txtSearchHD)
                    .addComponent(btnSearchHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbHoaDon.setBackground(java.awt.Color.white);
        tbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbHoaDon.setRowHeight(25);
        tbHoaDon.setShowGrid(true);
        tbHoaDon.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tbHoaDon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchHDActionPerformed

    private void txtSearchHDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchHDFocusGained
            txtSearchHD.setText("");
    }//GEN-LAST:event_txtSearchHDFocusGained

    
    //tim kiem theo MaHoaDon
    private void btnSearchHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchHDMouseClicked
       String text = txtSearchHD.getText();
        AtomicBoolean check = new AtomicBoolean();
        JOptionPane.showConfirmDialog(jDateChoiseHD, jDateChoiseHD.getDate());
        listHoaDon.forEach(s ->{
            if(s.getMaHD().toUpperCase().equals(text.toUpperCase())){
                check.set(true);
                 String[] title = { "MaHD", "Ngày Tạo", "Khách Hàng", "Số lượng", "Tổng Tiền", "Tiền Khách Đưa", "Nhân Viên", "Ghi Chú"};
		 modelTBHoaDon = new DefaultTableModel(title,0);
                 String[] rowData = {
				s.getMaHD(),changeDateToString(s.getNgayLapHD()),s.getMaKH(),String.valueOf(s.getSoLuong()),String.valueOf(s.getTongTien()),
                            String.valueOf(s.getTienKhachDua()),s.getMaNV(),s.getGhiChu()
			};
             modelTBHoaDon.addRow(rowData);
                tbHoaDon.setModel(modelTBHoaDon);
                btnShowHD.setEnabled(true);
            }
        });
        if(!check.get()){
           JOptionPane.showMessageDialog(btnSearchHD, "Không có Hóa Đơn có mã:" + text + " " );
        }
    }//GEN-LAST:event_btnSearchHDMouseClicked

    
    //click vao Hien thi lai ds HoaDon
    private void btnShowHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowHDMouseClicked
        btnShowHD.setEnabled(false);
        renderListHoaDon();
    }//GEN-LAST:event_btnShowHDMouseClicked

    private void jDateChoiseHDInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDateChoiseHDInputMethodTextChanged
        System.out.println(evt.getText());
    }//GEN-LAST:event_jDateChoiseHDInputMethodTextChanged

    private void jDateChoiseHDCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDateChoiseHDCaretPositionChanged
        // TODO add your handling code here:
         System.out.println(evt.getText());
    }//GEN-LAST:event_jDateChoiseHDCaretPositionChanged

    private void jDateChoiseHDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChoiseHDFocusLost
        // TODO add your handling code here:
         System.out.println(jDateChoiseHD.getDate());
    }//GEN-LAST:event_jDateChoiseHDFocusLost


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchHD;
    private javax.swing.JButton btnShowHD;
    private com.toedter.calendar.JDateChooser jDateChoiseHD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbHoaDon;
    private javax.swing.JTextField txtSearchHD;
    // End of variables declaration//GEN-END:variables
}
